# CircleCi config
version: 2
jobs:
  build:
    working_directory: ~/htdevelopers/efamilycare-web
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: v1-dep-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Tests
          command: yarn test --maxWorkers=4
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Cypress
          command: yarn cypress:server
      - store_test_results:
          path: /tmp/circleci-test-results
